apiVersion: v1
kind: Pod
metadata:
  name: nginx-crashloop
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    command:
    - /bin/sh
    - -c
    - |
      # Start nginx (triggers system calls)
      nginx -g "daemon off;" &
      # Intentionally cause a failure after a short delay
      sleep 2
      exit 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
  restartPolicy: Always
