apiVersion: v1
kind: Pod
metadata:
  name: nginx-crashloop
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    args:
    - invalid-command # Deliberate invalid argument
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
