apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sysdig
  template:
    metadata:
      labels:
        app: sysdig
    spec:
      containers:
        - name: sysdig
          image: sysdig/sysdig
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev-vol
              mountPath: /host/dev
            - name: proc-vol
              mountPath: /host/proc
            - name: boot-vol
              mountPath: /host/boot
            - name: modules-vol
              mountPath: /lib/modules
      volumes:
        - name: dev-vol
          hostPath:
            path: /dev
        - name: proc-vol
          hostPath:
            path: /proc
        - name: boot-vol
          hostPath:
            path: /boot
        - name: modules-vol
          hostPath:
            path: /lib/modules
